//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S.I.A.C.Models.DomainModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSIACEntities : DbContext
    {
        public dbSIACEntities()
            : base("name=dbSIACEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<module> module { get; set; }
        public virtual DbSet<operations> operations { get; set; }
        public virtual DbSet<people> people { get; set; }
        public virtual DbSet<priority> priority { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<rolOperations> rolOperations { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ticket> ticket { get; set; }
        public virtual DbSet<ticketHistory> ticketHistory { get; set; }
    }
}
