//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S.I.A.C.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class operations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public operations()
        {
            this.rolOperations = new HashSet<rolOperations>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int idModule { get; set; }
    
        public virtual module module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rolOperations> rolOperations { get; set; }
    }
}
