//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S.I.A.C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolOperations
    {
        public int id { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> idOperations { get; set; }
    
        public virtual operations operations { get; set; }
        public virtual rol rol { get; set; }
    }
}
